language: node_js
sudo: false

node_js:
  - "4"
  - "5"

env:
  - KAFKA_HOME=../kafka CXX=g++-4.8

before_install:
- wget http://www.us.apache.org/dist/kafka/0.9.0.1/kafka_2.10-0.9.0.1.tgz -O kafka.tgz
- mkdir -p ${KAFKA_HOME} && tar xzf kafka.tgz -C ${KAFKA_HOME} --strip-components 1
- echo 'delete.topic.enable=true' >> ${KAFKA_HOME}/config/server.properties
- sh test/utils/start_kafka.sh start

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: npm run coverage && (npm run coveralls || exit 0)
