spec: &spec
  x-sub-request-filters:
    - type: default
      name: http
      options:
        allow:
          - pattern: /^https?:\/\//
            forward_headers:
              user-agent: true
  title: The Change Propagation root
  paths:
    /sys/purge:
      x-modules:
        - path: sys/purge.js
          options:
            host: 127.0.0.1
            port: 4321
    /sys/links:
      x-modules:
        - path: sys/dep_updates.js
          options:
            templates:
              mw_api:
                  uri: 'https://{{message.meta.domain}}/w/api.php'
                  headers:
                    host: '{{message.meta.domain}}'
                  body:
                    formatversion: 2
    /sys/queue:
      x-modules:
        - path: sys/kafka.js
          options:
            metadata_broker_list: 127.0.0.1:9092
            dc_name: test_dc
            startup_delay: 0
            consumer:
              # These options should not be copied to puppet config.
              # We're using this config for testing, so need to configure
              # for minimal latency
              fetch.wait.max.ms: "1"
              fetch.min.bytes: "1"
              queue.buffering.max.ms: "1"
            concurrency: 250
            rules:
               - rules/ores.yaml
               - rules/restbase_deps.yaml
               - rules/restbase_updates.yaml
               - rules/redlinks.yaml
            templates:
              hosts:
                restbase: 'https://{{message.meta.domain}}/api/rest_v1'
                ores: 'https://ores.wikimedia.org'

              wikidata_description:
                topic: mediawiki.revision_create
                match:
                  meta:
                    domain: www.wikidata.org
                exec:
                  method: 'post'
                  uri: '/sys/links/wikidata_descriptions'
                  body: '{{globals.message}}'

              on_wikidata_description_change:
                topic: resource_change
                match:
                  meta:
                    uri: '/https:\/\/[^\/]+\/wiki\/(?<title>.+)/'
                  tags: [ 'change-prop', 'wikidata' ]
                exec:
                  method: get
                  uri: 'https://{{message.meta.domain}}/api/rest_v1/page/summary/{{match.meta.uri.title}}'
                  headers:
                    cache-control: no-cache
                  query:
                    redirect: false

num_workers: 0
logging:
  name: changeprop
  level: info
services:
  - name: changeprop
    module: hyperswitch
    conf:
      port: 7272
      user_agent: SampleChangePropInstance
      spec: *spec
