spec: &spec
  x-sub-request-filters:
    - path: lib/auth_http_filter.js
      options:
        username: 'SOME_USER_WILL_BE_HERE'
        password: 'SOME_PASSWORD_WILL_BE_HERE'
        hosts:
          - /^https?:\/\/secure.org/ # Private wiki
        templates:
          mw_api:
            method: 'post'
            uri: 'http://{{request.params.domain}}/w/api.php'
            headers:
              host: '{{request.params.domain}}'
    - type: default
      name: http
      options:
        allow:
          - pattern: /^https?:\/\//
            forward_headers:
              user-agent: true

  title: The Change Propagation root
  paths:
    /sys/queue:
      x-modules:
        - path: sys/kafka.js
          options:
            metadata_broker_list: 127.0.0.1:9092
            consume_dc: test_dc
            produce_dc: test_dc
            startup_delay: 0
            consumer:
              fetch.wait.max.ms: "1"
              fetch.min.bytes: "1"
              queue.buffering.max.ms: "1"
            concurrency: 1
            templates:
              simple_test_rule:
                topic: simple_test_rule
                retry_limit: 2
                retry_delay: 10
                retry_on:
                  status:
                    - '50x'
                    - 400
                ignore:
                  status:
                    - 403
                    - 412
                match:
                  meta:
                    uri: '/sample/uri'
                  message: 'test'
                exec:
                  method: post
                  uri: 'http://mock.com'
                  headers:
                    test_header_name: test_header_value
                    content-type: application/json
                  body:
                    test_field_name: test_field_value
                    derived_field: '{{message.message}}'
                    random_field: '{{message.random}}'
              redirect_testing_rule:
                topic: simple_test_rule
                match:
                  meta:
                    uri: '/sample/uri'
                  message: 'redirect'
                exec:
                  method: get
                  uri: 'http://mock.com/will_redirect'

              kafka_producing_rule:
                topic: kafka_producing_rule
                exec:
                  method: 'post'
                  uri: '/sys/queue/events'
                  body:
                    - meta:
                        topic: '{{message.produce_to_topic}}'
                        uri: '{{message.meta.uri}}'
                        request_id: '{{message.meta.request_id}}'
                      message: 'test'
                      triggered_by: '{{message.meta.topic}}:{{message.meta.uri}}'
                    - meta:
                        topic: '{{message.produce_to_topic}}'
                        uri: '{{message.meta.uri}}'
                        request_id: '{{message.meta.request_id}}'
                      message: 'test'
                      triggered_by: '{{message.meta.topic}}:{{message.meta.uri}}'

              secure_rule:
                topic: simple_test_rule
                match:
                  meta:
                    uri: '/secure/uri'
                exec:
                  method: get
                  uri: 'http://secure.org/test'

num_workers: 0
logging:
  name: changeprop
  level: trace
services:
  - name: changeprop
    module: hyperswitch
    conf:
      user_agent: ChangePropTestSuite
      port: 7272
      spec: *spec